queue:
	# Compiling the queue implemantation
	# Compilando a implementacao da fila
	gcc -c queue.c
	
	# Compiling and generating the executable
	# Compilando e gerando o executavel
	gcc main.c queue.o -o main
	
	# Executing
	# Executando
	./main

clean:
	rm *.o	
	rm main
	